# Config.toml example https://github.com/Vimux/Mainroad/

baseurl = "https://myhelper4.netlify.app/"
#baseurl = "/"

title =  "myHelper4" # bez ovoga ne prikazuje logo
#languageCode =  ["en-us", "hr-hr"]
paginate = "10" # Number of posts per page
theme = "mainroad"
#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id


# not sure I need this
# [permalinks]
#  posts = '/:monthname/:year/:title/'
# posts = '/:title/'
# OR…
# [permalinks]
# posts = "/:slug"


 DefaultContentLanguage = "en"
 defaultContentLanguageInSubdir = true

 [languages]

   [languages.en]
    languageName = "English"
    languageNameShort = "EN"
    languageFlag = "🇬🇧"
    weight = 1
    contentDir = "content/en"

      [[languages.en.menu.main]] 
      identifier = "home"
      name = " "
      url = "/en/"
      pre = "<span class='menuItemHome'>&nbsp;&nbsp;&nbsp;&nbsp;</span>"
      weight = 1

      [[languages.en.menu.main]]
        name = "Hugo"
        url = "/en/tags/hugo/"
         weight = 20
      [[languages.en.menu.main]]
         name = "Linux"
         url = "/en/tags/linux/"
         weight = 30
      [[languages.en.menu.main]]
         name = "JS"
         url = "/en/tags/js/"
         weight = 40

   [languages.hr]
     languageName = 'Hrvatski'
     languageNameShort = "HR"
     languageFlag = "🇭🇷"
     weight = 2
     contentDir = "content/hr"

      [[languages.hr.menu.main]]
      name = " "
      url = "/hr/"
      weight = 3
      pre = "<span class='menuItemHome'>&nbsp;&nbsp;&nbsp;&nbsp;</span>"

      [[languages.hr.menu.main]]
        name = "Hugo"
        url = "/hr/tags/hugo/"
         weight = 4

      [[languages.hr.menu.main]]
        name = "Linux"
        url = "/hr/tags/linux/"
         weight = 5

      [[languages.hr.menu.main]]
        name = "Js"
        url = "/hr/tags/js/"
         weight = 6




#disableKinds = [] #["page", "section", "taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]
#disableKinds = ["sitemap"]


[outputs] # ovo treba za search - ne diraj
  home = ["HTML", "JSON", "RSS"] # ovo treba za search - ne diraj
  #home = ["HTML", "JSON"] # ovo treba za search - ne diraj
  page = ["HTML", "RSS"]
  # section = ["HTML"]
  # taxonomyTerm = ["HTML"]
  # taxonomy = ["HTML"]

# in Front matter to disable "sitemap_ignore" and/or "rss_ignore" add
# sitemap_ignore: true
# rss_ignore: true    

# https://tekki-tipps.de/en/use-php-in-hugo/
# [mediaTypes]
#   [mediaTypes."application/x-php"]
#   suffixes = ["php"]

# [outputFormats]
#   [outputFormats.PHP]
#     mediaType = "application/x-php"
#     isPlainText = true
#     baseName = "index"


[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

# Enable html tags in .md file (ex. <iframe> )
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#     unsafe = true

# https://gohugo.io/hugo-modules/configuration/#module-config-mounts
# with this loading images from assets/images folder
[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'

[params]
  description = "My Helper 4 is esentially a How to... of things I use with Hugo, css, js, linux, windows ect." # Description of your site
  opengraph = false # Enable OpenGraph if true
  schema = false # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true false
  authorbox = true  # Show authorbox at bottom of pages if true
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["hugo", "linux", "markdown", "posts"] # ["post", "blog", "news"] Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02.01.2006" # Change the format of dates
  copyright =  "© myHelper4. - "  # upisano u partial/footer.html
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files

# [params.logo]
# image ="/images/logo_helper4.svg" # img defined in partial/logo.html
# subtitle = "Helper 4" # Logo subtitle

# ignorefiles = [ "/php/\\.*" ]

[params.style.vars]
  highlightColor = "#656ef6" # Override highlight color 656ef6 5596bc
  # purple 656ef6 7b8ae0 #5e35b1
  # blie-purple 2f2e8b 2e85b2 0f3e72
  # red f60038  d44a4a a83e40 903639 5d0e34 c31432
  # tirkiz dark 0085a1
  # tirkiz darker 007d9c
  # tirkiz 4ac0cf 00dfc4

  #secondHighlightColor = "#a3a8fa" # Override secondHighlightColor color
  #backHighlightColor = "#fff"

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  # fontFamilyPrimary = "'Source Sans Pro', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[params.featured]
  featured_num = 2 # number of featured posts, shown only on home page 

[params.imagecredit]
  enableimagecredit = true

[params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages false
  # Enable widgets in given order
   widgets = [ "categories", "taglist" ]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["search","ddg-search", "recent", "categories", "taglist", "social", "languages"]

[params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
  categories_counter = true # Enable counter for each category in "Categories" widget

#[params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
   # github = "hartegg"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"

enableRobotsTXT = true


# see https://gohugo.io/about/hugo-and-gdpr/    
  # [privacy]
  #   [privacy.disqus]
  #     disable = false
  #   [privacy.googleAnalytics]
  #     disable = false
  #     anonymizeIP = true
  #     respectDoNotTrack = true
  #   [privacy.instagram]
  #     disable = false
  #     simple = true
  #   [privacy.twitter]
  #     disable = false
  #     enableDNT = true
  #     simple = false
  #   [privacy.vimeo]
  #     disable = false
  #     enableDNT = true
  #     simple = true
  #   [privacy.youtube]
  #     disable = false
  #     privacyEnhanced = true
 