# Config.toml example https://github.com/Vimux/Mainroad/

baseurl = "/"
#baseurl = "/"

title =  "myHelper4" # bez ovoga ne prikazuje logo
languageCode = "en-us" # ["en-us", "hr-hr"]
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "G-V2DPHNV1QQ" # Enable Google Analytics by entering your tracking id



# [permalinks]
#  posts = '/:monthname/:year/:title/'
# posts = '/:title/'
# OR…
# [permalinks]
# posts = "/:slug"


# DefaultContentLanguage = "en"
# [languages]
#   [languages.en]
#     title = "My Helper 4"
#     languageName = "English"
#     weight = 1
#   [languages.hr]
#     title = "My Helper 4"
#     languageName = "Hrvatski"
#     weight = 2


#disableKinds = [] #["page", "section", "taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]
#disableKinds = ["sitemap"]

#[Author]
  # name = "ikm"
  # bio = "Do or do not there is no trying"
  # avatar = "img/avatar.png"

[outputs] # ovo treba za search - ne diraj
  home = ["HTML", "JSON", "RSS"] # ovo treba za search - ne diraj
  #home = ["HTML", "JSON"] # ovo treba za search - ne diraj
  page = ["HTML", "RSS"]
  # section = ["HTML"]
  # taxonomyTerm = ["HTML"]
  # taxonomy = ["HTML"]

#https://codingnconcepts.com/hugo/custom-rss-feed-hugo/#add-full-content-in-rssxml
# ovo ne radi, ne generira rss
# [outputFormats]
#   [outputFormats.RSS]
#     mediatype = "application/rss"
#     baseName = "rss"
    
# in Front matter to disable "sitemap_ignore" and "rss_ignore" add
# sitemap_ignore: true
# rss_ignore: true    

# https://tekki-tipps.de/en/use-php-in-hugo/
# [mediaTypes]
#   [mediaTypes."application/x-php"]
#   suffixes = ["php"]

# [outputFormats]
#   [outputFormats.PHP]
#     mediaType = "application/x-php"
#     isPlainText = true
#     baseName = "index"


[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

# Enable html tags in .md file (ex. <iframe> )
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#     unsafe = true

# https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#  BEZ OVOG NE UČITAVA SLIKE IZ assets FOLDERA
[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'


[params]
  description = "Helper 4..." # Description of your site
  opengraph = false # Enable OpenGraph if true
  schema = false # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true false
  authorbox = true  # Show authorbox at bottom of pages if true
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["posts", "blog", "news"] # ["post", "blog", "news"] Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02.01.2006" # Change the format of dates
  copyright =  "© myHelper4. - "  # upisano u partial/footer.html
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files

# [params.logo]
# image ="/images/logo_helper4.svg" # slika definirana u partial logo.html
# subtitle = "Helper 4" # Logo subtitle

# ignorefiles = [ "/php/\\.*" ]

[params.style.vars]
  highlightColor = "#656ef6" # Override highlight color 656ef6 5596bc
  # ljubičasta 656ef6
  # ljubičasta2 7b8ae0
  # crvena f60038  d44a4a a83e40 903639 5d0e34 c31432
  # tirkiz tamni 0085a1
  # tirkiz tamni2 007d9c
  # tirkiz 4ac0cf         00dfc4
  # plavo-ljubičasta 2f2e8b 2e85b2 0f3e72
  #secondHighlightColor = "#a3a8fa" # Override secondHighlightColor color
  #backHighlightColor = "#fff"

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  # fontFamilyPrimary = "'Source Sans Pro', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[params.thumbnail]
  visibility = ["list", "post"] # ["list", "post"]  Control thumbnail visibility

[params.featured]
  featured_num = 2 # number of featured posts, shown only on home page 

[params.imagecredit]
  enableimagecredit = true

[params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages false
  # Enable widgets in given order
  widgets = [ "categories", "taglist"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["search","ddg-search", "recent", "categories", "taglist", "social", "languages"]

[params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
  categories_counter = true # Enable counter for each category in "Categories" widget

[params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"

enableRobotsTXT = true

menu = ['main', 'footer']

[menu]

  [[menu.main]]
      identifier = "home"
      name = " "
     # pre = "<svg class='svg-inline fa-home' aria-hidden='true' focusable='false' data-prefix='fas' data-icon='house' role='img' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 500' data-fa-i2svg=''><path fill='currentColor' d='M575.8 255.5C575.8 273.5 560.8 287.6 543.8 287.6H511.8L512.5 447.7C512.5 450.5 512.3 453.1 512 455.8V472C512 494.1 494.1 512 472 512H456C454.9 512 453.8 511.1 452.7 511.9C451.3 511.1 449.9 512 448.5 512H392C369.9 512 352 494.1 352 472V384C352 366.3 337.7 352 320 352H256C238.3 352 224 366.3 224 384V472C224 494.1 206.1 512 184 512H128.1C126.6 512 125.1 511.9 123.6 511.8C122.4 511.9 121.2 512 120 512H104C81.91 512 64 494.1 64 472V360C64 359.1 64.03 358.1 64.09 357.2V287.6H32.05C14.02 287.6 0 273.5 0 255.5C0 246.5 3.004 238.5 10.01 231.5L266.4 8.016C273.4 1.002 281.4 0 288.4 0C295.4 0 303.4 2.004 309.5 7.014L564.8 231.5C572.8 238.5 576.9 246.5 575.8 255.5L575.8 255.5z'/></svg>"
     # pre = "<img src='images/home.png' />"
       pre = "<span class='menuItemHome'>&nbsp;&nbsp;&nbsp;&nbsp;</span>"
      url = "/"
      weight = 1

  [[menu.main]]
      identifier = "hugo"
      name = "Hugo"
      url = "/tags/hugo/"
      weight = 3
  
  [[menu.main]]
      identifier = "linux"
      name = "Linux"
      url = "/tags/linux/"
      weight = 4
  
    [[menu.main]]
      identifier = "js"
      name = "Js"
      url = "/tags/js/"
      weight = 5

    [[menu.main]]
      identifier = "html"
      name = "Html"
      url = "/tags/html/"
      weight = 5

    [[menu.main]]
      identifier = "css"
      name = "Css"
      url = "/tags/css/"
      weight = 5

  [[menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 6
     
      # [[menu.main]]
      #   identifier = "contact"
      #   name = "Contact"
      #   url = "/contact/"
      #   parent = "contact"
      #   weight = 7


  [[menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1
  [[menu.footer]]
      identifier = "faq"
      name = "Faq"
      url = "/faq/"
      weight = 2

  [[menu.footer]]
      identifier = "contact"
      name = "Contact"
      url = "/categories/contact/"
      weight = 3


# see https://gohugo.io/about/hugo-and-gdpr/    
  # [privacy]
  #   [privacy.disqus]
  #     disable = false
  #   [privacy.googleAnalytics]
  #     disable = false
  #     anonymizeIP = true
  #     respectDoNotTrack = true
  #   [privacy.instagram]
  #     disable = false
  #     simple = true
  #   [privacy.twitter]
  #     disable = false
  #     enableDNT = true
  #     simple = false
  #   [privacy.vimeo]
  #     disable = false
  #     enableDNT = true
  #     simple = true
  #   [privacy.youtube]
  #     disable = false
  #     privacyEnhanced = true
 
